baseURL = 'https://jadens-arc.github.io/'
languageCode = 'en-us'
title = 'Jaden Arceneaux'
copyright = "Â© Jaden Arceneaux"
paginate=5 # articles per page
# Code Highlight
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

theme = "archie"

[params]
  og_image="/icon.png"
  subtitle="Software Developer based in Las Vegas, Nevada"
	description = "Software Developer based in Las Vegas, Nevada"
	mode="toggle"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
  customcss = ["css/custom.css"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jadens-arc"


[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jaden-arceneaux/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/jaden.svg"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
