baseURL = 'https://jadenarceneaux.com'
languageCode = 'en-us'
title = 'Jaden Arceneaux'
copyright = "Â© Jaden Arceneaux"
paginate = 5                           # articles per page
# Code Highlight
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

theme = "archie"

[params]
og_image = "/icon.png"
subtitle = "Software Developer and occacional writer"
description = "Software Developer based in Las Vegas, Nevada"
mode = "toggle"
mathjax = true                                                # enable MathJax support
katex = true                                                  # enable KaTeX support
customcss = ["css/custom.css"]
enableRobotsTXT = true

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jadens-arc"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/jaden.svg/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jaden-arceneaux/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:contact@jadenarceneaux.com"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4

[[menu.main]]
name = "Misc"
url = "/misc"
weight = 5
