baseURL = 'https://jadens-arc.github.io/'
languageCode = 'en-us'
title = 'Jaden Arceneaux'
copyright = "© Jaden Arceneaux"
theme = "github.com/jadens-arc/archie"
paginate=3 # articles per page

[params]
    subtitle = "Just me lol"
	mode="toggle" # color-mode → light,dark,toggle or auto
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support


# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jadens-arc"


[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jaden-arceneaux/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Articles"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4

